### ISSUE TITLE
Running without options

### ISSUE THREAD

**Issue by fabaff** [kaiiyer/webtech#6]
After installing `webtech` I get this traceback.

```bash
$ webtech
Traceback (most recent call last):
  File "/usr/bin/webtech", line 11, in <module>
    load_entry_point('webtech==1.2.5', 'console_scripts', 'webtech')()
  File "/usr/lib/python3.7/site-packages/webtech/__main__.py", line 54, in main
    wt.start()
  File "/usr/lib/python3.7/site-packages/webtech/webtech.py", line 130, in start
    for url in self.urls:
TypeError: 'NoneType' object is not iterable
```

Can you please create a new release as 1.2.5 which is available on PyPI doesn't include the updated check? Thanks

**Comment by kaiiyer** [comment]
I've updated it to version 1.2.5 and added some fixes.
Can you check if it works fine now
